{% set version = "1.0.0" %}

package:
  name: jupyter-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-cache/jupyter_cache-{{ version }}.tar.gz
  sha256: d0fa7d7533cd5798198d8889318269a8c1382ed3b22f622c09a9356521f48687

build:
  number: 0
  noarch: python
  entry_points:
    - jcache = jupyter_cache.cli.commands.cmd_main:jcache
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python >=3.9
  run:
    - attrs
    - click
    - importlib-metadata
    - nbclient >=0.2
    - nbformat
    - python >=3.9
    - pyyaml
    - sqlalchemy >=1.3.12,<3
    - tabulate

test:
  imports:
    - jupyter_cache
    - jupyter_cache.cache
  commands:
    - pip check
    - jcache --version
    - jcache --help
    - jcache --version | grep -iE "{{ version.replace('.', '\.') }}$"
  requires:
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/executablebooks/jupyter-cache
  summary: A defined interface for working with a cache of jupyter notebooks.
  license: MIT
  license_file: LICENSE
  doc_url: https://jupyter-cache.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
